-- Drop the bad trigger that generates stub vocabulary entries
DROP TRIGGER IF EXISTS trigger_ensure_article_vocabulary ON articles;
DROP FUNCTION IF EXISTS ensure_article_vocabulary() CASCADE;
DROP FUNCTION IF EXISTS generate_vocab_for_article(uuid) CASCADE;
DROP FUNCTION IF EXISTS extract_significant_words(text, int) CASCADE;

-- Remove all stub vocabulary entries (those with placeholder meanings)
-- These were generated by the old trigger and have no real dictionary data
UPDATE articles
SET story = jsonb_set(
  story,
  '{vocabulary}',
  (
    SELECT COALESCE(jsonb_agg(elem), '[]'::jsonb)
    FROM jsonb_array_elements(COALESCE(story->'vocabulary', '[]'::jsonb)) AS elem
    WHERE elem->>'meaning' IS NOT NULL
      AND elem->>'meaning' NOT IN (
        'A significant term used in this article.',
        'An important word from the story.',
        'Detailed examination of something to understand it better.'
      )
      AND elem->>'meaning' NOT LIKE 'A significant term used in this article%'
      AND elem->>'meaning' NOT LIKE 'An important word from the story%'
  ),
  true
)
WHERE is_published = true
  AND story IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM jsonb_array_elements(COALESCE(story->'vocabulary', '[]'::jsonb)) AS elem
    WHERE elem->>'meaning' IN (
        'A significant term used in this article.',
        'An important word from the story.',
        'Detailed examination of something to understand it better.'
    )
    OR elem->>'meaning' LIKE 'A significant term used in this article%'
    OR elem->>'meaning' LIKE 'An important word from the story%'
  );

-- Also remove entries with empty meanings or empty words
UPDATE articles
SET story = jsonb_set(
  story,
  '{vocabulary}',
  (
    SELECT COALESCE(jsonb_agg(elem), '[]'::jsonb)
    FROM jsonb_array_elements(COALESCE(story->'vocabulary', '[]'::jsonb)) AS elem
    WHERE elem->>'word' IS NOT NULL
      AND length(trim(elem->>'word')) >= 3
      AND elem->>'meaning' IS NOT NULL
      AND length(trim(elem->>'meaning')) >= 10
  ),
  true
)
WHERE is_published = true
  AND story IS NOT NULL;